"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import socket from "./utils/socket";
import { useEffect } from "react";
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  useEffect(() => {
    function onConnect() {
      console.log('socket is connected!!')
      socket.io.engine.on('upgrade', (transport) => {
        console.log({ 'transport': transport.name })
      })
    }

    function onDisconnect() {
      console.log('socket is disconnected!!')
    }

    if (socket.connected) {
      onConnect()
    }

    socket.on('connected', onConnect)
    socket.on('disconnect', onDisconnect)

    return () => {
      socket.off('connected', onConnect)
      socket.off('disconnect', onDisconnect)
    }
  }, [])


  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header>
            <NavBar/>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
